### ISSUE TITLE
Allow passing params to policies in the requests config

### ISSUE THREAD

**Issue by viniciusdacal** [viniciusdacal/redux-arc#1]
Currently, the only way to provide params to the policies is by add them when you call the creator.

Would be better to allow passing the params in the requests configs. This way, we could use a policy this way:

```js
const { creators, types } = createApiActions('namespace', {
  list: {
    url: 'enpoint',
    method: 'get',
    policies: ['anyPolicy', { name: 'policyWithParams', ...params }]
  }
});
```

**Comment by viniciusdacal** [comment]
Policies now are middlewares and we are going to remove the registration concept and start importing the middleware and providing it directly to the config.

**Comment by jamestowers** [comment]
So is it possible now to pass params to middlewares? I'm creating a `redirectMiddleware` which will redirect the user on successful response, ie. after login but I'd like to pass in an optional url to redirect to

**Comment by viniciusdacal** [comment]
Yes, it's.
The second argument of a `creator` is the `meta`, which can be used to provide any extra data that is not going to be used as the payload:
```js
dispatch(creators.list(payload, meta));
```
Then, inside the middleware, or any other place you have access to the action:
```js
const { meta } = action;
....
```

**Comment by viniciusdacal** [comment]
Oh, with the new middlewares api, there's also another way...
Since now you import the middleware and provide it explicitly in the middlewares array, you could make your middleware as a factory.
eg:

```js
export const myMiddlewareFactory = (middlewareParams) => {
  function myMiddleware() {
    return done => (action, error, response) => done(action, error, response);
  }
  myMiddleware.applyPoint = 'onResponse';

  return myMiddleware;
};

export default myMiddlewareFactory();
```
Then, inside the action definition:

```js
import { createActions } from 'redux-arc';
import { myMiddlewareFactory } from './myMiddleware';

const { types, actions } = createActions('todo', {
  list:   {
    url: '/api/todo',
    method: 'get',
    middlewares: [myMiddlewareFactory(paramsToMiddleware)],
  },
});
```
Notice I let the export default already executing the factory, so, if you want to use the middleware without providing any params, you could just import the default export.

Pick the approach that you think it's cleaner (meta vs middlewareFactory)

**Comment by jamestowers** [comment]
Nice! I like that second option, thanks.
