### ISSUE TITLE
Global middlewares

### ISSUE THREAD

**Issue by jamestowers** [viniciusdacal/redux-arc#18]
Is there a way to add global middlewares to every request?

I want to add a `token` string to every request (if there currently is one), at the moment i'd have to do something like this on every creator

```js
const { types, creators } = createActions('posts', {
  list: {
    url: 'posts',
    method: 'get',
    middlewares: [addTokenMiddleware],
  },
})
```

Also, do we have access to the redux state from middlewares? I'd like the get the token from the state and add it if it exists

**Comment by jamestowers** [comment]
To answer my second question, i see you can pass the store variable into the middleware and then use `getState()` 

```js
const addSessionToRequestMiddleware = store => done => (action, error, response) => {
  const { payload, meta } = action
  const token = store.getState().auth.token
  ...
```

**Comment by jamestowers** [comment]
OK thanks, that's what I ended up doing, like this:

```js
const asyncTask = store => done => (options) => {
  // eslint-disable-next-line no-unused-vars
  const { url, method, payload, ...meta } = options

  const token =  store.getState().auth.token

  const payloadWithToken = payload || {}
  payloadWithToken.token = token

  // add body params or queryParams
  const params = method === 'get' ? { params: payloadWithToken } : payloadWithToken
  ...
```

**Comment by viniciusdacal** [comment]
Awesome! I will try to create a recipes section in the docs with these common usages.
Any future doubts, let me know.
Thank you
