### ISSUE TITLE
Merge passed payload with defaults

### ISSUE THREAD

**Issue by jamestowers** [viniciusdacal/redux-arc#19]
Is there a way to merge the payload passed to the action creator with the defaults provided in `createActions` ?

I have the following `createActions`:

```js
export const { creators, types } = createActions('posts', {
  ...
  list: {
    url: '/posts/retrieve',
    method: 'get',
    payload: {
      'options[next]': 0,
      'options[limiter]': 0,
      'options[size]': 10,
      'filter[mode]': 'archive'
    }
  }
...
})
```

which is called from:

```js
const mapDispatchToProps = (dispatch) => {
  const payload = {
    'options[next]': 0,
    'options[limiter]': 0,
    'options[size]': 10,
    'filter[mode]': 'drafts'
  }
  return {
    fetchData: () => { dispatch(posts.list(payload)) }
  }
}
```

but it would be nice if we could do:

```js
const mapDispatchToProps = (dispatch) => {
  const payload = {
    'filter[mode]': 'drafts'
  }
  return {
    fetchData: () => { dispatch(posts.list(payload)) }
  }
}
```

and the payload would get merged with the defaults

**Comment by viniciusdacal** [comment]
Yes, there is.
We assign the configs to each creator, so, you should be able to do `posts.list.payload`, which is the payload you provided in the configs. 
Considering that, you could do:

```js
const mapDispatchToProps = (dispatch) => {
  const payload = {
    ...posts.list.payload,
    'filter[mode]': 'archive'
  }
  return {
    fetchData: () => { dispatch(posts.list(payload)) }
  }
}
```
Let me know if that works for you

**Comment by jamestowers** [comment]
OK that works well, thanks! It would be nice if we didn't even have to worry about doing `...posts.list.payload,` though :-)

**Comment by viniciusdacal** [comment]
I agree, merging the payloads directly could be tricky though.
I mean, we could do a shallow merge, but then would be cases when we would need a deep merge.

So, considering the edge cases, we don't assume much about use cases, but we leave Arc's API very flexible to allow you implement them.

Let me know your future doubts. 

Thank you.
