### ISSUE TITLE
Appending state item to async task url

### ISSUE THREAD

**Issue by jamestowers** [viniciusdacal/redux-arc#21]
Me again....

Many of the api endpoints in our application require a `profileId` in the url, eg: 

```/articles/:profileId/:id```

The `profileId` is stored in the state and previously, when using redux-saga (which we are replacing with redux-arc 🙂) we could get it before making the api call.

Is there a smart way of doing this with redux-arc?

We could intercept the api call with a middleware and detect the `:profileId` in the url with regex and replace it with the item from the state?

Currently we are getting it in `mapStateToProps` then passing down to the component then back up to `mapDispatchToProps` via event handlers which feels a bit messy

**Comment by viniciusdacal** [comment]
The url parsing happens before the middlewares, so, if you would like to use a middleware to do that, you would have to use a different marker in the url, such as `/articles/_PROFILE_ID_/:id`.

But I think I have a better solution.

When you are defining the arc's action configs, the url can be a string or it can be a function,  which will receive the  `meta` and should return the proper url. Eg:

```js
const { creators, types } = createActions('user', {
  read: { url: (meta) => `/user/${meta.id}` }
});

creators.read(null, { id: 123 });
```
With that in mind, we could create a function that gets the profileId in the state, and creates a url with it.

First, you will have to export your store instance, so, you can import in other places and use
```js
store.getState()
```
Considering you have that....

Let's create a function `injectProfileId`, which will expect a url to be parsed. 

```js
import parseUrl from 'redux-arc/lib/parseUrl';
import store from 'path/to/store';

const injectProfileId = (url) => (meta) => {
  const { profileId } = store.getState().user;

  return parseUrl(url, {...meta, profileId });
};
```
First, `injectProfileId` will expect a url, then, it returns the actual function that arc's config will use.

Arc has a function `parseUrl`, that we use internally to parse the urls that comes in the configs, we can import and use that. The first argument should be the url and the second, should be the params that will be used to parse it.

Finally, the action config.
```js

const { creators, types } = createActions('namespace', {
  getArticles: {
    url: injectProfileId('/articles/:profileId/:id'),
    method: 'get',
  }
});

```

You can put injectProfileId into a utils file, so, whenever you need to have the profileId in the url, you just import and use it.

Let me know if you decide to use that approach and need some help.

**Comment by jamestowers** [comment]
That works perfectly, thanks @viniciusdacal
