### ISSUE TITLE
Best way to prevent a unnecessary async request

### ISSUE THREAD

**Issue by jamestowers** [viniciusdacal/redux-arc#22]
What would be the best way to cancel an api request if we already have the data in the store?

Something similar to the `shouldFetchPosts` method here https://redux.js.org/advanced/async-actions#actions.js-(with-fetch)

**Comment by viniciusdacal** [comment]
Hey,
You could use a middleware + factory to do that:

```js
function fetchIfNeededFactory(shouldFetch) {
  function fetchIfNeeded(store) {
    return done => (action, error, response) => {
      const state = store.getState();
      if (shouldFetch(state, action)) {
        return done(action, error, response)
      }

    };
  }
  fetchIfNeeded.applyPoint = 'onRequest';
}

```
Observe that we don't do anything when it should not fetch the data; In that case, the action was intercept, and will never go to the next middleware, neither will do the request.

About the factory, you can create the middlewares for specific resources.
The posts example would be like this:

```js
const shouldFetchPosts = fetchIfNeededFactory((state, action) => {
  const posts = state.postsBySubreddit[action.meta.subreddit]
   if (!posts) {
     return true;
   }
   
   if (posts.isFetching) {
     return false;
   }
   return posts.didInvalidate;
});
```
Notice that will you have access to the redux state and the action you dispatched, so, that should be enough for you "shouldFetch" logic.

The `shouldFetchPosts` is your middleware, so, you can just provide it in the `createActions` config
