### ISSUE TITLE
Error: attempting to change value of a readonly property

### ISSUE THREAD

**Issue by oraziocontarino** [viniciusdacal/redux-arc#24]
Environment:  
- npm: v6.0.0
- package.json:  
  ```
    "expo": "^27.0.1",
    "native-base": "^2.7.0",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-odoo": "^0.5.0",
    "react-native-side-menu": "^1.1.3",
    "react-native-table-component": "^1.1.8",
    "react-navigation": "^2.6.2",
    "react-navigation-redux-helpers": "^2.0.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-arc": "^0.7.3",
    "redux-thunk": "^2.3.0",
    "rnpm": "^1.9.0",
    "xmldom": "^0.1.27"
  ```
I'm developing a React Native Expo app. It've set the Strict Mode (Expo do it as default).  
In this scenario when fsaActionCreatorFactory.js try to execute the following code:
```
...
  Object.defineProperty(actionCreator, 'name', {
    value: type + ' action creator',
    writable: false
  });
...
```
the error on the attached image is printed out.
![ErrorImage](https://user-images.githubusercontent.com/18686793/42638369-bd618648-85ed-11e8-87d4-5478f7f6d0b4.PNG).  
The property name of the function `actionCreator` is set as `read only`. In this way we are trying to force a "set value" and this is forbidden.
If I run the app in debug mode (with Strict Mode deactivated) it works fine!

**Comment by kde3kko** [comment]
I have the same exact problem when importing redux-arc in an Expo project bootstrapped with the `create-react-native-app` script.
I will deactivate the Strict Mode now (thanks @oraziocontarino  !)
Please let me know if i can be of any help.

**Comment by viniciusdacal** [comment]
bug fixed here 923bfbd
0.7.4 is out.
Please, let us know if that completely fixed the bug, then we can close the issue 😃

**Comment by oraziocontarino** [comment]
@kde3kko 
> edit: How do I deactivate Strict Mode in an Expo project?  
I don't know, i'm a beginner too in Expo and React Apps developments.  
@viniciusdacal 
> As said in first post, it seems to work (i have commented the function that you have just removed and after a week of development the error has not occurred anymore).

**Comment by kde3kko** [comment]
Yes, I confirm it's working now.
Thanks a lot for the support, and kudos for the awesome work on arc!

**Comment by viniciusdacal** [comment]
Glad to hear that! 😸 Will close the issue then. 🥇
