### ISSUE TITLE
Optional query parameters in GET async actions

### ISSUE THREAD

**Issue by kde3kko** [viniciusdacal/redux-arc#25]
Hi, 
At work we're successfully using this library in both a React and React Native project and it saved us a ton of boilerplate code (perhaps you remember me since the previous  compilation issue with react native :-) ).
We're now at the point where we'd like to have a way to set optional query parameters in GET requests to tell our backend how to filter data.

Example:
To my knowledge, the library provides the current options to make a GET request to an example resource ( I added a possible back end expected response on the right based on our current back end behaviour)

| Request | BE response |
|----|----|
|`GET resource/` | all exams |
|`GET resource/:customParameter`| single resource based on customParameter (like `id`)|

I'd like to have a way to add query parameters to the get request, such as:

| Request | BE response |
|----|----|
| `GET resource/?exampleFilter=:someCustomFIlter` | n resources based on exampleFilter parameter (_exampleFilter could be any parameter name and should be parametrized in some way as well as the payload_) |

We went on with this by duplicating and dispatching different custom actions (each one for every possible query params, since we only have like 3 or 4 combinations and just in some specific cases).
Is there a "smarter" way to do this?
Am I missing something?

Thank you very much, and again, kudos for the great work on this library.

**Comment by viniciusdacal** [comment]
Hey, Glad to know that arc is helping in your project.

When you are doing a GET request, the action payload will become the query parameters.
Eg.
```js
dispatch(creators.list({ exampleFilter: 'filtervalue' }));
```
Also, you need to configure your asyncTask function to understand that. in this link there's an example using axios:
[https://redux-arc.js.org/#async-middleware](https://redux-arc.js.org/#async-middleware).

The difference is that we check the method, and if it is `get`, we use the action payload as the params.

Please, let me know if that works for you.

Thanks :)

**Comment by kde3kko** [comment]
Man, that's great, exactly what I was hoping for!
I've been putting `null` as first parameter in every GET request dispatch, using the url string to manually compose the query string inside `createActions`...how silly!
It all makes sense now.
Well, time to refactor a whole bunch of code... :-)

Thanks a lot!
